requires 'Mojolicious';
requires 'Mojo::UserAgent';
requires 'JSON';
requires 'Try::Tiny';
requires 'Redis';
requires 'Mojo::Log';
requires 'Math::Random::Secure';
requires 'Time::Piece';
requires 'IO::Socket::SSL';
